import Head from 'next/head'
import { Inter } from '@next/font/google'
import Navbar from '@/components/Navbar'
import SliderHome from '@/components/Sliders/home'
import Section from '@/components/Section'
import Footer from '@/components/Footer'
import HomeComp from '@/components/Home'
import SecComp from '@/components/Home/sec'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>e-cargo.mn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=''>
        <Navbar/>
        <HomeComp/>
        {/* <SliderHome/> */}
        <Section/>
        <SecComp/>
          {/* <img className='w-full' src='/../../background/cargo.png'/> */}
        <Footer/>
      </div>
    </>
  )
}
