import Head from 'next/head'
import { Inter } from '@next/font/google'
import Navbar from '@/components/Navbar'
import SliderHome from '@/components/Sliders/home'
import Section from '@/components/Section'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>e-cargo.mn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-gray-100'>
        <Navbar/>
        <SliderHome/>
        <Section/>
      </div>
    </>
  )
}
